url: https://heikkihei.github.io
baseurl: /portfolio/

# Site settings
title: Mun portfolio.
description: "Hajaantukaa, täällä ei ole mitään nähtävää."


# Team names, titles and social links
people:
- name: Heikki Ahonen
  pic: 1
  position: Tietotekniikan lehtori.
  social:
    - title: twitter
      url: https://twitter.com/HeikkiHei
    - title: github
      url: https://github.com/HeikkiHei

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/HeikkiHei
  - title: github
    url: https://github.com/HeikkiHei

# Postal address (add as many lines as necessary)
# address:
#  - line: 3481 Melrose Place
#  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty