url: https://heikkihei.github.io
baseurl: /portfolio/

# Site settings
title: My Portfolio
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Heikki Ahonen
  pic: 1
  position: Lecturer
  social:
    - title: twitter
      url: https://twitter.com/HeikkiHei
    - title: GitHub
      url: https://github.com/HeikkiHei

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
  social:
    - title: twitter
      url: https://twitter.com/HeikkiHei
    - title: GitHub
      url: https://github.com/HeikkiHei

# Postal address (add as many lines as necessary)
# address:
#  - line: 3481 Melrose Place
#  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty